  -
    name: "default"
    #folder: "c:\\delete\\destDir\\beautiful_images"
    folder: "/home/kovalchuk/test/destDir/beautiful_images"
    start: 00:00:00
    end: 23:59:59
    priority: 0
  -
    name: "news"
    #folder: "c:\\delete\\destDir\\news"
    folder: "/home/kovalchuk/test/destDir/news"
    start: 11:03:00
    end: 11:10:00
    priority: 10
  -
    name: "news"
    #folder: "c:\\delete\\destDir\\news"
    folder: "/home/kovalchuk/test/destDir/news"
    start: 11:20:00
    end: 11:30:00
    priority: 10
  -
    name: "news"
    #folder: "c:\\delete\\destDir\\news"
    folder: "/home/kovalchuk/test/destDir/news"
    start: 11:40:00
    end: 11:50:00
    priority: 10
  -
    name: "announces"
    #folder: "c:\\delete\\destDir\\announce"
    folder: "/home/kovalchuk/test/destDir/announce"
    start: 11:05:00
    end: 11:15:00
    priority: 20
  -
    name: "announces"
    #folder: "c:\\delete\\destDir\\announce"
    folder: "/home/kovalchuk/test/destDir/announce"
    start: 11:25:00
    end: 11:35:00
    priority: 20
